CREATE DATABASE checkpoint4;
USE checkpoint4;
CREATE TABLE question ( id INT NOT NULL AUTO_INCREMENT, question VARCHAR(255) NOT NULL, PRIMARY KEY(id));
CREATE TABLE theme ( id INT NOT NULL AUTO_INCREMENT, theme VARCHAR(45) NOT NULL, PRIMARY KEY (id));
INSERT INTO theme (theme) VALUES('Office chit-chat');
INSERT INTO theme (theme) VALUES('Get to know someone');
INSERT INTO theme (theme) VALUES('Friends Party');
INSERT INTO theme (theme) VALUES('Family Business');

CREATE TABLE question_has_theme ( question_id INT NOT NULL,  theme_id INT NOT NULL,  PRIMARY KEY (question_id, theme_id), CONSTRAINT questionTheme_fk FOREIGN KEY (question_id) REFERENCES question(id),  CONSTRAINT Theme_fk FOREIGN KEY (theme_id) REFERENCES theme(id) );

INSERT INTO question (question) VALUES('Quel est ton premier souvenir ?');
INSERT INTO question (question) VALUES('Qui voulais-tu être quand tu étais enfant ?');
INSERT INTO question (question) VALUES('Si tu gagnais au loto demain, arrêterais- tu de travailler ? Si oui, que ferais-tu à la place ?');
INSERT INTO question (question) VALUES('Raconte moi une chose les gens ne savent habituellement pas sur toi');
INSERT INTO question (question) VALUES('Cite une de tes chansons préférées. Raconte pourtant tu l’aimes autant.');
INSERT INTO question (question) VALUES('Aimerais -tu vivre dans un autre pays ? Si oui, lequel et pourquoi ?');
INSERT INTO question (question) VALUES("Si tes amis devaient te présenter, qu'aimerais-tu qu'ils disent de toi ?");
INSERT INTO question (question) VALUES('Fais-tu facilement confiance ?');
INSERT INTO question (question) VALUES('Si je ne pouvais pas te voir, comment te décrirais-tu ?');
INSERT INTO question (question) VALUES('Parle d’une personne qui compte ou a compté beaucoup pour toi');
INSERT INTO question (question) VALUES("Quel type de vacances aimes tu ? (aventure, plage, hotel, l'autre bout du monde, à côté,...)");
INSERT INTO question (question) VALUES('Cite 3 valeurs qui sont importantes pour toi');
INSERT INTO question (question) VALUES('Quels liens entretiens-tu avec ta famille ?');
INSERT INTO question (question) VALUES("Quelles sont les traditions de Noël dans ta famille s'il y en a ?");
INSERT INTO question (question) VALUES("Quel est le plus beau compliment qu'on t'ai fait ?");

INSERT INTO question_has_theme (question_id, theme_id) VALUES (1,1);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (1,2);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (1,3);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (1,4);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (2,3);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (2,1);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (3,2);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (3,3);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (3,4);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (4,2);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (5,1);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (5,2);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (6,1);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (6,2);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (6,3);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (6,4);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (7,1);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (7,2);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (8,2);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (8,3);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (9,2);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (10,1);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (10,2);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (10,3);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (10,4);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (11,4);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (11,1);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (12,1);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (12,2);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (12,3);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (13,2);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (13,3);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (14,2);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (14,3);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (15,1);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (15,2);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (15,3);
INSERT INTO question_has_theme (question_id, theme_id) VALUES (15,4);